std = "lua51"
max_line_length = false
codes = true
exclude_files = {
	"**/libs",
}
only = {
	"011", -- syntax
	"1", -- globals
}
ignore = {
	"11/SLASH_.*", -- slash handlers
	"1/[A-Z][A-Z][A-Z0-9_]+", -- three letter+ constants
}
globals = {
	-- wow std api
	"abs",
	"acos",
	"asin",
	"atan",
	"atan2",
	"bit",
	"ceil",
	"cos",
	"date",
	"debuglocals",
	"debugprofilestart",
	"debugprofilestop",
	"debugstack",
	"deg",
	"difftime",
	"exp",
	"fastrandom",
	"floor",
	"forceinsecure",
	"foreach",
	"foreachi",
	"format",
	"frexp",
	"geterrorhandler",
	"getglobal",
	"getn",
	"gmatch",
	"gsub",
	"hooksecurefunc",
	"issecure",
	"issecurevariable",
	"ldexp",
	"log",
	"log10",
	"max",
	"min",
	"mod",
	"rad",
	"random",
	"scrub",
	"securecall",
	"seterrorhandler",
	"sin",
	"sort",
	"sqrt",
	"strbyte",
	"strchar",
	"strcmputf8i",
	"strconcat",
	"strfind",
	"string.join",
	"string.split",
	"strjoin",
	"strlen",
	"strlenutf8",
	"strlower",
	"strmatch",
	"strrep",
	"strrev",
	"strsplit",
	"strsub",
	"strtrim",
	"strupper",
	"table.wipe",
	"tan",
	"time",
	"tinsert",
	"tremove",

	-- framexml
	"BackdropTemplateMixin",
	"ChatFrame1",
	"Enum",
	"InterfaceOptions_AddCategory",
	"InterfaceOptionsFrame_OpenToCategory",
	"InterfaceOptionsFrame",
	"InterfaceOptionsFramePanelContainer",
	"Minimap",
	"SlashCmdList",
	"StaticPopup_Show",
	"StaticPopupDialogs",
	"ToggleDropDownMenu",
	"UIDropDownMenu_AddButton",
	"UIDropDownMenu_Initialize",
	"UIParent",
	"WorldMapFrame",

	-- blizzard api and xml
	"C_ChatInfo",
	"C_DeathInfo",
	"C_Map",
	"C_PetBattles",
	"C_QuestLog",
	"C_TaskQuest",
	"CreateFrame",
	"GetAddOnMetadata",
	"GetBuildInfo",
	"GetCVar",
	"GetCVarBool",
	"GetLocale",
	"GetPlayerFacing",
	"GetQuestUiMapID",
	"InCombatLockdown",
	"IsAltKeyDown",
	"IsControlKeyDown",
	"IsInInstance",
	"IsLoggedIn",
	"IsShiftKeyDown",
	"PlaySoundFile",
	"QuestPOIGetIconInfo",
	"QuestPOIUpdateIcons",
	"SetCVar",
	"SetPortraitTextureFromCreatureDisplayID",
	"UnitIsDeadOrGhost",
	"UnitName",
	"UnitOnTaxi",
	"WorldMapMixin",

	-- TomTom-defined	
	"LibStub",
	"TomTom",
	"TomTomBlock",
	"TomTomCrazyArrow",
	"TomTomLocals",
	"TomTomMapOverlay",
	"TomTomWorldFrame",
}
